spring:
  data:
    rest:
      basePath: /api
  datasource:
    url: ${db.url}
    driverClassName: ${db.driver.name}
    username: ${db.username}
    password: ${db.password}
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/changelog-master.yml"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
