#server:
#  servlet:
#    context-path: /super-lib
spring:
#  mongodb:
#    embedded:
#      version: "3.5.5"
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library_db
  mongock:
    runner-type: InitializingBean
    change-logs-scan-package:
      - ru.otus.projs.hw11.changelogs
