server:
  port: 8001
spring:
  application:
    name: eureka-discovery-server

## Standalone Eureka settings
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8001/eureka"
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    registry-sync-retries: 3
    max-threads-for-peer-replication: 0
