spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: new_library_db
  datasource:
    url: jdbc:h2:mem:old_library
    driverClassName: org.h2.Driver
    username: admin
    password: qwerty
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/changelog-master.yml"
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      path: /h2
      settings:
          web-allow-others: true
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true


#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#        security:
#          web:
#            FilterChainProxy: DEBUG
