spring:
  messages:
    basename: "messages/message"
    encoding: "UTF-8"
management:
  endpoints:
    web:
      exposure:
        include: health, beans, info


### params
app:
  params:
    testPassLimit: 4
    locale: ru_RU
  files:
    csvQuestions: "/questions_${app.params.locale}.csv"

