spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library_db
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.projs.hw08.changelogs
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


